name: CI pipe run and build

#.gihub/workflows/CI_pipe2.yml
on:
  push:
    branches:
      - "main"

jobs:
  compile:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: List of repo
        run: ls ${{ github.workspace }}
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
  build-docker:
    runs-on: ubuntu-latest
    needs:
      - compile
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag flask-app:$(date +%s)