name: hello-world

# on: push
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  hello-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: pwd
  job-2:
    runs-on: ubuntu-latest
    steps:
       - name: step3
         run: ls